# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresstype', models.IntegerField(default=1)),
                ('hnum', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=255)),
                ('subdivision', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.IntegerField()),
                ('secnumber', models.IntegerField()),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roletype', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalsales', models.FloatField(default=0)),
                ('sproducttype', models.FloatField(default=0)),
                ('sproduct', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('mi', models.CharField(max_length=3)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='watche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default=0, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('use', models.IntegerField(default=0)),
                ('picture', models.ImageField(default='items/default_item.jpg', upload_to='items/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aionApp.watche'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aionApp.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aionApp.watche'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aionApp.user'),
        ),
        migrations.AddField(
            model_name='addresse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aionApp.user'),
        ),
    ]
