# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresse',
            old_name='addresstype',
            new_name='address_type',
        ),
        migrations.RenameField(
            model_name='addresse',
            old_name='hnum',
            new_name='home_number',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='cardnumber',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='secnumber',
            new_name='security_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mi',
            new_name='middle_initial',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='addresse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='users',
        ),
        migrations.RemoveField(
            model_name='review',
            name='watch',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='watch',
        ),
        migrations.RemoveField(
            model_name='watche',
            name='picture',
        ),
        migrations.AddField(
            model_name='addresse',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='watch_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='watch_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watche',
            name='watch_id',
            field=models.IntegerField(default=0),
        ),
    ]
