# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0002_auto_20180304_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_addres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('house_number', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=255)),
                ('subdivision', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='shipping_addres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('house_number', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=255)),
                ('subdivision', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='addresse',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='roletype',
            new_name='role_type',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='sproduct',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='sproducttype',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='totalsales',
            new_name='total_sales',
        ),
    ]
