# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0004_auto_20180304_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='role',
        ),
        migrations.RemoveField(
            model_name='watche',
            name='use',
        ),
        migrations.AddField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('3', 'Users'), ('2', 'Administrator'), ('0', 'Product Users'), ('1', 'Accounting Manager')], default='3', max_length=16),
        ),
        migrations.AddField(
            model_name='watche',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watche',
            name='watch_type',
            field=models.CharField(choices=[('0', 'Analog'), ('1', 'Digital'), ('2', 'Smart')], default='0', max_length=16),
        ),
    ]
