# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0005_auto_20180306_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('3', 'User'), ('0', 'Product Manager'), ('2', 'Administrator'), ('1', 'Accounting Manager')], default='3', max_length=16),
        ),
    ]
