# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0008_watche_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='watche',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
