# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0009_watche_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_addres',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='shipping_addres',
            name='user_id',
        ),
    ]
