# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0010_auto_20180308_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='billing_addres',
            name='postal_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shipping_addres',
            name='postal_code',
            field=models.CharField(max_length=255),
        ),
    ]
