# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0013_auto_20180308_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watche',
            name='description',
            field=models.CharField(default=0, max_length=2048),
        ),
    ]
