# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0014_auto_20180308_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watche',
            name='picture',
            field=models.ImageField(default='media/no-img.jpg', upload_to='media/'),
        ),
    ]
