# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0016_auto_20180309_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watche',
            name='watch_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
