# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0018_auto_20180310_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_watche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('picture', models.ImageField(default='media/no-img.jpg', upload_to='watchPictures/')),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='watche',
            name='quantity',
        ),
    ]
