# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0019_auto_20180310_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aionApp.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='watch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aionApp.watche'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='watch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aionApp.watche'),
        ),
        migrations.AlterField(
            model_name='watche',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aionApp.user'),
        ),
    ]
