# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0020_auto_20180310_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watche',
            name='id',
        ),
        migrations.AlterField(
            model_name='watche',
            name='watch_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
