# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0020_auto_20180311_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hello',
            new_name='buy_watche',
        ),
    ]
