# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0021_auto_20180310_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watche',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
