# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0023_auto_20180311_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_watche',
            name='watch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aionApp.watche'),
        ),
    ]
