# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0027_checkout_watch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='total',
        ),
    ]
