# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0028_remove_checkout_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_watche',
            name='description',
            field=models.CharField(default=0, max_length=2048),
        ),
        migrations.AlterField(
            model_name='buy_watche',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
