# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0029_auto_20180312_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='watch_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='watch_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
