# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0031_auto_20180312_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
