# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0033_auto_20180312_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='watche',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
