# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0036_auto_20180415_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_addres',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shipping_addres',
            name='name',
        ),
    ]
