# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0038_auto_20180417_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(default=0, max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('username', models.CharField(default=0, max_length=255)),
                ('location', models.CharField(default=0, max_length=255)),
                ('action', models.CharField(default=0, max_length=255)),
                ('result', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
