# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0040_account_log_product_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sale',
        ),
    ]
