# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0041_delete_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='billing_add',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_add',
        ),
    ]
