# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0042_auto_20180419_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_addres',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipping_addres',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
