# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aionApp', '0045_auto_20180419_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sale',
        ),
    ]
